<script setup lang="ts">
import HeadingSmall from '@/components/HeadingSmall.vue';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import AppLayout from '@/layouts/AppLayout.vue';
import type { BreadcrumbItem, Menu } from '@/types';
import { Head, Link, router } from '@inertiajs/vue3';
import { ExclamationTriangleIcon } from '@heroicons/vue/24/solid';
import {
    ArrowLeft,
    ChevronDown,
    CopyIcon,
    Loader2,
    Plus,
    Save,
    Search,
    Sparkles,
    Trash2,
} from 'lucide-vue-next';
import { computed, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

const { t } = useI18n();

interface LocaleMeta {
    native: string;
    flag: string;
    code: string;
}

interface TranslationFields {
    name: string;
    description: string;
}

interface IngredientTranslation {
    id: number;
    name: string;
    translations: Record<string, Partial<{ name: string }>> | null;
}

interface SectionWithProducts {
    id: number;
    name: string;
    description: string | null;
    translations: Record<string, Partial<TranslationFields>> | null;
    products: Array<{
        id: number;
        name: string;
        description: string | null;
        translations: Record<string, Partial<TranslationFields>> | null;
        ingredients?: IngredientTranslation[];
    }>;
}

type MenuWithSections = Omit<Menu, 'sections'> & {
    sections: SectionWithProducts[];
    translations?: Record<string, Partial<TranslationFields>> | null;
};

interface Props {
    menu: MenuWithSections;
    hasMultilang: boolean;
    autoGenerated?: boolean;
    sourceLocale: string;
    supportedLocales: Record<string, LocaleMeta>;
    enabledLocales: string[];
}

const props = defineProps<Props>();

// ---------- State ----------
const breadcrumbItems = computed<BreadcrumbItem[]>(() => [
    { title: t('translations.menus_breadcrumb'), href: `/panel/locations/${props.menu.location_id}/menus` },
    { title: props.menu.name, href: `/panel/menus/${props.menu.id}` },
    { title: t('translations.breadcrumb'), href: '#' },
]);

const targetLocales = computed(() => props.enabledLocales.filter((l) => l !== props.sourceLocale));
const activeLocale = ref<string>(targetLocales.value[0] ?? '');

const availableToAdd = computed(() =>
    Object.values(props.supportedLocales).filter(
        (l) => l.code !== props.sourceLocale && !props.enabledLocales.includes(l.code),
    ),
);

// Form state: per-locale buckets for menu, sections, products, ingredients.
interface LocaleForm {
    menu: TranslationFields;
    sections: Record<number, TranslationFields>;
    products: Record<number, TranslationFields>;
    ingredients: Record<number, { name: string }>;
}

const form = reactive<Record<string, LocaleForm>>({});

function hydrateLocale(code: string) {
    const bucket: LocaleForm = {
        menu: {
            name: props.menu.translations?.[code]?.name ?? '',
            description: props.menu.translations?.[code]?.description ?? '',
        },
        sections: {},
        products: {},
        ingredients: {},
    };
    for (const section of props.menu.sections ?? []) {
        bucket.sections[section.id] = {
            name: section.translations?.[code]?.name ?? '',
            description: section.translations?.[code]?.description ?? '',
        };
        for (const product of section.products ?? []) {
            bucket.products[product.id] = {
                name: product.translations?.[code]?.name ?? '',
                description: product.translations?.[code]?.description ?? '',
            };
            for (const ingredient of product.ingredients ?? []) {
                bucket.ingredients[ingredient.id] = {
                    name: ingredient.translations?.[code]?.name ?? '',
                };
            }
        }
    }
    form[code] = bucket;
}

// Hydrate all currently enabled target locales.
for (const code of targetLocales.value) {
    hydrateLocale(code);
}

// Track snapshot for dirty detection.
const initialSnapshot = ref<string>(JSON.stringify(form));
const isDirty = computed(() => JSON.stringify(form) !== initialSnapshot.value);

// ---------- Search & collapse ----------
const searchQuery = ref('');
const normalizedQuery = computed(() => searchQuery.value.trim().toLowerCase());

const collapsedSections = reactive<Record<number, boolean>>({});

function matchesSearch(section: SectionWithProducts): boolean {
    if (!normalizedQuery.value) return true;
    if (section.name.toLowerCase().includes(normalizedQuery.value)) return true;
    return section.products.some((p) => p.name.toLowerCase().includes(normalizedQuery.value));
}

function visibleProducts(section: SectionWithProducts) {
    if (!normalizedQuery.value) return section.products;
    if (section.name.toLowerCase().includes(normalizedQuery.value)) return section.products;
    return section.products.filter((p) => p.name.toLowerCase().includes(normalizedQuery.value));
}

function toggleSection(id: number) {
    collapsedSections[id] = !collapsedSections[id];
}

function expandAll() {
    for (const s of props.menu.sections) collapsedSections[s.id] = false;
}

function collapseAll() {
    for (const s of props.menu.sections) collapsedSections[s.id] = true;
}

// ---------- Progress ----------
function isFilled(v: string | null | undefined): boolean {
    return typeof v === 'string' && v.trim() !== '';
}

function progressFor(code: string): { done: number; total: number } {
    if (!form[code]) return { done: 0, total: 0 };
    let total = 0;
    let done = 0;

    // Menu fields (only count if source has content)
    if (isFilled(props.menu.name)) {
        total++;
        if (isFilled(form[code].menu.name)) done++;
    }
    if (isFilled(props.menu.description)) {
        total++;
        if (isFilled(form[code].menu.description)) done++;
    }
    for (const s of props.menu.sections ?? []) {
        if (isFilled(s.name)) {
            total++;
            if (isFilled(form[code].sections[s.id]?.name)) done++;
        }
        if (isFilled(s.description)) {
            total++;
            if (isFilled(form[code].sections[s.id]?.description)) done++;
        }
        for (const p of s.products ?? []) {
            if (isFilled(p.name)) {
                total++;
                if (isFilled(form[code].products[p.id]?.name)) done++;
            }
            if (isFilled(p.description)) {
                total++;
                if (isFilled(form[code].products[p.id]?.description)) done++;
            }
            for (const ing of p.ingredients ?? []) {
                if (isFilled(ing.name)) {
                    total++;
                    if (isFilled(form[code].ingredients[ing.id]?.name)) done++;
                }
            }
        }
    }
    return { done, total };
}

function sectionMissingCount(section: SectionWithProducts): number {
    if (!activeLocale.value || !form[activeLocale.value]) return 0;
    const bucket = form[activeLocale.value];
    let missing = 0;
    if (isFilled(section.name) && !isFilled(bucket.sections[section.id]?.name)) missing++;
    if (isFilled(section.description) && !isFilled(bucket.sections[section.id]?.description)) missing++;
    for (const p of section.products ?? []) {
        if (isFilled(p.name) && !isFilled(bucket.products[p.id]?.name)) missing++;
        if (isFilled(p.description) && !isFilled(bucket.products[p.id]?.description)) missing++;
        for (const ing of p.ingredients ?? []) {
            if (isFilled(ing.name) && !isFilled(bucket.ingredients[ing.id]?.name)) missing++;
        }
    }
    return missing;
}

// ---------- Actions ----------
const saving = ref(false);
const addingLocale = ref<string | null>(null);
const removingLocale = ref<string | null>(null);

function copyFromSource(target: 'menu' | 'section' | 'product' | 'ingredient', id: number, field: 'name' | 'description') {
    if (!activeLocale.value || !form[activeLocale.value]) return;
    if (target === 'menu') {
        form[activeLocale.value].menu[field] = (props.menu[field] as string | null) ?? '';
        return;
    }
    if (target === 'section') {
        const s = props.menu.sections.find((x) => x.id === id);
        if (!s) return;
        form[activeLocale.value].sections[id][field] = (s[field] as string | null) ?? '';
        return;
    }
    if (target === 'product') {
        for (const s of props.menu.sections) {
            const p = s.products.find((x) => x.id === id);
            if (p) {
                form[activeLocale.value].products[id][field] = (p[field] as string | null) ?? '';
                return;
            }
        }
    }
    if (target === 'ingredient') {
        for (const s of props.menu.sections) {
            for (const p of s.products) {
                const ing = (p.ingredients ?? []).find((x) => x.id === id);
                if (ing) {
                    if (!form[activeLocale.value].ingredients[id]) {
                        form[activeLocale.value].ingredients[id] = { name: '' };
                    }
                    form[activeLocale.value].ingredients[id].name = ing.name ?? '';
                    return;
                }
            }
        }
    }
}

function copyAllFromSource() {
    if (!activeLocale.value || !form[activeLocale.value]) return;
    if (!confirm(t('translations.copy_originals_confirm'))) return;
    const bucket = form[activeLocale.value];
    bucket.menu.name = props.menu.name ?? '';
    bucket.menu.description = props.menu.description ?? '';
    for (const s of props.menu.sections) {
        bucket.sections[s.id].name = s.name ?? '';
        bucket.sections[s.id].description = s.description ?? '';
        for (const p of s.products) {
            bucket.products[p.id].name = p.name ?? '';
            bucket.products[p.id].description = p.description ?? '';
            for (const ing of p.ingredients ?? []) {
                if (!bucket.ingredients[ing.id]) bucket.ingredients[ing.id] = { name: '' };
                bucket.ingredients[ing.id].name = ing.name ?? '';
            }
        }
    }
}

function save() {
    saving.value = true;

    // Build payload: merge each target locale bucket into existing translations.
    const menuTranslations: Record<string, TranslationFields> = { ...(props.menu.translations ?? {}) } as Record<string, TranslationFields>;
    for (const code of targetLocales.value) {
        if (form[code]) menuTranslations[code] = { ...form[code].menu };
    }

    const sectionsPayload = props.menu.sections.map((s) => {
        const t: Record<string, TranslationFields> = { ...(s.translations ?? {}) } as Record<string, TranslationFields>;
        for (const code of targetLocales.value) {
            if (form[code]?.sections[s.id]) t[code] = { ...form[code].sections[s.id] };
        }
        return { id: s.id, translations: t };
    });

    const productsPayload: Array<{ id: number; translations: Record<string, TranslationFields> }> = [];
    const ingredientsPayload: Array<{ id: number; translations: Record<string, { name: string }> }> = [];
    for (const s of props.menu.sections) {
        for (const p of s.products) {
            const t: Record<string, TranslationFields> = { ...(p.translations ?? {}) } as Record<string, TranslationFields>;
            for (const code of targetLocales.value) {
                if (form[code]?.products[p.id]) t[code] = { ...form[code].products[p.id] };
            }
            productsPayload.push({ id: p.id, translations: t });

            for (const ing of p.ingredients ?? []) {
                const it: Record<string, { name: string }> = { ...(ing.translations ?? {}) } as Record<string, { name: string }>;
                for (const code of targetLocales.value) {
                    if (form[code]?.ingredients[ing.id]) it[code] = { ...form[code].ingredients[ing.id] };
                }
                ingredientsPayload.push({ id: ing.id, translations: it });
            }
        }
    }

    router.put(
        `/panel/menus/${props.menu.id}/translations`,
        {
            menu: { translations: menuTranslations },
            sections: sectionsPayload,
            products: productsPayload,
            ingredients: ingredientsPayload,
        } as never,
        {
            preserveScroll: true,
            onFinish: () => {
                saving.value = false;
                initialSnapshot.value = JSON.stringify(form);
            },
        },
    );
}

function addLanguage(code: string) {
    addingLocale.value = code;
    router.post(
        `/panel/menus/${props.menu.id}/translations/add-language`,
        { locale: code } as never,
        {
            preserveScroll: true,
            onFinish: () => {
                addingLocale.value = null;
            },
        },
    );
}

function removeLanguage(code: string) {
    if (!confirm(t('translations.remove_language_confirm', { name: labelFor(code).native }))) return;
    removingLocale.value = code;
    router.delete(`/panel/menus/${props.menu.id}/translations/language`, {
        data: { locale: code } as never,
        preserveScroll: true,
        onFinish: () => {
            removingLocale.value = null;
        },
    });
}

function labelFor(code: string): LocaleMeta {
    return (
        props.supportedLocales[code] ?? {
            code,
            native: code.toUpperCase(),
            flag: '🏳️',
        }
    );
}

// If activeLocale drops out of targetLocales (e.g., after remove), snap to first.
watch(targetLocales, (locales) => {
    if (!locales.includes(activeLocale.value)) {
        activeLocale.value = locales[0] ?? '';
    }
});
</script>

<template>
    <Head :title="`${t('translations.title')} — ${menu.name}`" />

    <AppLayout :breadcrumbs="breadcrumbItems">
        <div class="flex h-full flex-1 flex-col gap-5 rounded-xl p-4 pb-24">
            <!-- Header -->
            <div class="flex items-center gap-4">
                <Button variant="outline" size="icon" as-child>
                    <Link :href="`/panel/menus/${menu.id}`">
                        <ArrowLeft class="h-4 w-4" />
                    </Link>
                </Button>
                <HeadingSmall
                    :title="t('translations.title')"
                    :description="t('translations.subtitle', { name: menu.name })"
                />
            </div>

            <!-- Upgrade required -->
            <Alert
                v-if="!hasMultilang"
                class="border-amber-500 bg-amber-50 text-amber-900 dark:bg-amber-950 dark:text-amber-200"
            >
                <ExclamationTriangleIcon class="size-4 text-amber-600" />
                <AlertTitle>{{ t('translations.upgrade_title') }}</AlertTitle>
                <AlertDescription>
                    {{ t('translations.upgrade_body') }}
                    <Link href="/panel/billing/plans" class="ml-1 font-semibold underline underline-offset-2">
                        {{ t('translations.view_plans') }}
                    </Link>
                </AlertDescription>
            </Alert>

            <!-- Auto-gen banner -->
            <Alert
                v-if="hasMultilang && autoGenerated"
                class="border-emerald-500 bg-emerald-50 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200"
            >
                <Sparkles class="size-4 text-emerald-600" />
                <AlertTitle>{{ t('translations.auto_generated_title') }}</AlertTitle>
                <AlertDescription>
                    {{ t('translations.auto_generated_body') }}
                </AlertDescription>
            </Alert>

            <template v-if="hasMultilang">
                <!-- Language tabs -->
                <div class="rounded-xl border bg-card text-card-foreground">
                    <div class="flex items-center gap-2 overflow-x-auto border-b px-3 py-2">
                        <!-- Source locale (non-clickable reference) -->
                        <div class="flex items-center gap-2 rounded-lg border border-dashed bg-muted/30 px-3 py-2 text-xs text-foreground">
                            <span class="text-base leading-none">{{ labelFor(sourceLocale).flag }}</span>
                            <span class="font-medium">{{ labelFor(sourceLocale).native }}</span>
                            <span class="rounded bg-foreground/10 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider">{{ t('translations.original') }}</span>
                        </div>

                        <!-- Target locale tabs -->
                        <button
                            v-for="code in targetLocales"
                            :key="code"
                            type="button"
                            class="group flex items-center gap-2 rounded-lg border px-3 py-2 text-xs transition-colors"
                            :class="[
                                activeLocale === code
                                    ? 'border-primary bg-primary/10 text-foreground shadow-sm'
                                    : 'border-transparent hover:border-border hover:bg-muted/60',
                            ]"
                            @click="activeLocale = code"
                        >
                            <span class="text-base leading-none">{{ labelFor(code).flag }}</span>
                            <span class="font-medium">{{ labelFor(code).native }}</span>
                            <span
                                class="rounded-full px-1.5 py-0.5 text-[10px] font-semibold tabular-nums"
                                :class="
                                    progressFor(code).done === progressFor(code).total && progressFor(code).total > 0
                                        ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300'
                                        : 'bg-foreground/10 text-foreground/80'
                                "
                            >
                                {{ progressFor(code).done }}/{{ progressFor(code).total }}
                            </span>
                            <Loader2 v-if="removingLocale === code" class="ml-0.5 h-3 w-3 animate-spin" />
                            <button
                                v-else
                                type="button"
                                class="ml-0.5 rounded-full p-0.5 text-muted-foreground opacity-0 transition-opacity hover:bg-destructive/10 hover:text-destructive group-hover:opacity-100"
                                :title="t('translations.remove_language_title', { name: labelFor(code).native })"
                                @click.stop="removeLanguage(code)"
                            >
                                <Trash2 class="h-3 w-3" />
                            </button>
                        </button>

                        <!-- Add language -->
                        <DropdownMenu v-if="availableToAdd.length > 0">
                            <DropdownMenuTrigger as-child>
                                <button
                                    type="button"
                                    class="flex items-center gap-1.5 rounded-lg border border-dashed px-3 py-2 text-xs font-medium text-muted-foreground transition-colors hover:border-primary hover:bg-primary/5 hover:text-primary"
                                    :disabled="addingLocale !== null"
                                >
                                    <Plus v-if="!addingLocale" class="h-3.5 w-3.5" />
                                    <Loader2 v-else class="h-3.5 w-3.5 animate-spin" />
                                    {{ t('translations.add_language') }}
                                </button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="start" class="min-w-[180px]">
                                <DropdownMenuItem
                                    v-for="meta in availableToAdd"
                                    :key="meta.code"
                                    class="flex cursor-pointer items-center gap-2"
                                    @click="addLanguage(meta.code)"
                                >
                                    <span>{{ meta.flag }}</span>
                                    <span>{{ meta.native }}</span>
                                    <Sparkles class="ml-auto h-3 w-3 text-emerald-500" />
                                </DropdownMenuItem>
                            </DropdownMenuContent>
                        </DropdownMenu>
                    </div>

                    <!-- Progress bar for active locale -->
                    <div v-if="activeLocale" class="px-4 py-3">
                        <div class="mb-1.5 flex items-center justify-between text-xs">
                            <span class="font-medium text-foreground">
                                {{ t('translations.progress_in', { language: labelFor(activeLocale).native }) }}
                            </span>
                            <span class="tabular-nums text-muted-foreground">
                                {{ t('translations.progress_fields', { done: progressFor(activeLocale).done, total: progressFor(activeLocale).total }) }}
                            </span>
                        </div>
                        <div class="h-1.5 w-full overflow-hidden rounded-full bg-muted">
                            <div
                                class="h-full bg-primary transition-all duration-500"
                                :style="{
                                    width:
                                        progressFor(activeLocale).total === 0
                                            ? '0%'
                                            : `${(progressFor(activeLocale).done / progressFor(activeLocale).total) * 100}%`,
                                }"
                            />
                        </div>
                    </div>
                </div>

                <!-- Controls bar -->
                <div v-if="activeLocale" class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                    <div class="relative flex-1 max-w-sm">
                        <Search class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                        <Input
                            v-model="searchQuery"
                            :placeholder="t('translations.search_placeholder')"
                            class="panel-input pl-9"
                        />
                    </div>
                    <div class="flex items-center gap-2">
                        <Button variant="ghost" size="sm" @click="expandAll">
                            <ChevronDown class="mr-1 h-3.5 w-3.5" />
                            {{ t('translations.expand') }}
                        </Button>
                        <Button variant="ghost" size="sm" @click="collapseAll">
                            <ChevronDown class="mr-1 h-3.5 w-3.5 rotate-180" />
                            {{ t('translations.collapse') }}
                        </Button>
                        <Button variant="outline" size="sm" @click="copyAllFromSource">
                            <CopyIcon class="mr-1.5 h-3.5 w-3.5" />
                            {{ t('translations.copy_originals') }}
                        </Button>
                    </div>
                </div>

                <!-- Menu-level translation -->
                <div
                    v-if="activeLocale"
                    class="rounded-xl border bg-card text-card-foreground p-5"
                >
                    <div class="mb-4 flex items-center gap-2">
                        <span class="rounded bg-primary/15 px-2 py-0.5 text-[11px] font-bold uppercase tracking-wider text-primary">
                            {{ t('translations.menu_label') }}
                        </span>
                        <h3 class="text-sm font-semibold">{{ t('translations.menu_section_title') }}</h3>
                    </div>
                    <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
                        <div class="space-y-1.5">
                            <Label class="panel-label-muted">{{ t('translations.field_name') }} · {{ labelFor(sourceLocale).flag }} {{ sourceLocale.toUpperCase() }}</Label>
                            <Input :model-value="menu.name" disabled class="panel-input-readonly" />
                        </div>
                        <div class="space-y-1.5">
                            <div class="flex items-center justify-between">
                                <Label class="panel-label">
                                    {{ t('translations.field_name') }} · {{ labelFor(activeLocale).flag }} {{ activeLocale.toUpperCase() }}
                                </Label>
                                <button
                                    type="button"
                                    class="text-[10px] text-muted-foreground hover:text-primary"
                                    :title="t('translations.copy_from_source')"
                                    @click="copyFromSource('menu', menu.id, 'name')"
                                >
                                    <CopyIcon class="h-3 w-3" />
                                </button>
                            </div>
                            <Input v-model="form[activeLocale].menu.name" class="panel-input" :placeholder="t('translations.name_placeholder')" />
                        </div>
                        <div class="space-y-1.5 md:col-span-1">
                            <Label class="panel-label-muted">{{ t('translations.field_description') }} · {{ sourceLocale.toUpperCase() }}</Label>
                            <Textarea :model-value="menu.description ?? ''" disabled rows="2" class="panel-input-readonly resize-none" />
                        </div>
                        <div class="space-y-1.5 md:col-span-1">
                            <div class="flex items-center justify-between">
                                <Label class="panel-label">{{ t('translations.field_description') }} · {{ activeLocale.toUpperCase() }}</Label>
                                <button
                                    type="button"
                                    class="text-[10px] text-muted-foreground hover:text-primary"
                                    :title="t('translations.copy_from_source')"
                                    @click="copyFromSource('menu', menu.id, 'description')"
                                >
                                    <CopyIcon class="h-3 w-3" />
                                </button>
                            </div>
                            <Textarea v-model="form[activeLocale].menu.description" rows="2" class="panel-input resize-none" :placeholder="t('translations.description_placeholder')" />
                        </div>
                    </div>
                </div>

                <!-- Sections -->
                <template v-if="activeLocale">
                    <template v-for="section in menu.sections" :key="section.id">
                        <div
                            v-if="matchesSearch(section)"
                            class="overflow-hidden rounded-xl border bg-card text-card-foreground"
                        >
                            <!-- Section header (clickable, collapsible) -->
                            <button
                                type="button"
                                class="flex w-full items-center justify-between gap-3 px-5 py-4 text-left transition-colors hover:bg-muted/30"
                                @click="toggleSection(section.id)"
                            >
                                <div class="flex min-w-0 items-center gap-3">
                                    <ChevronDown
                                        class="h-4 w-4 flex-shrink-0 text-muted-foreground transition-transform"
                                        :class="collapsedSections[section.id] ? '-rotate-90' : ''"
                                    />
                                    <div class="min-w-0">
                                        <h3 class="truncate text-sm font-semibold">
                                            {{ section.name }}
                                        </h3>
                                        <p class="mt-0.5 text-xs text-muted-foreground">
                                            {{ t('translations.count_dishes', { count: section.products.length }, section.products.length) }}
                                        </p>
                                    </div>
                                </div>
                                <span
                                    v-if="sectionMissingCount(section) > 0"
                                    class="flex-shrink-0 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700 dark:bg-amber-950 dark:text-amber-300"
                                >
                                    {{ t('translations.pending_fields', { count: sectionMissingCount(section) }) }}
                                </span>
                                <span
                                    v-else
                                    class="flex-shrink-0 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-semibold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"
                                >
                                    {{ t('translations.complete') }}
                                </span>
                            </button>

                            <div v-show="!collapsedSections[section.id]" class="border-t">
                                <!-- Section fields -->
                                <div class="space-y-4 bg-muted/10 px-5 py-4">
                                    <p class="text-[11px] font-bold uppercase tracking-wider text-foreground/60">
                                        {{ t('translations.section_label') }}
                                    </p>
                                    <div class="grid grid-cols-1 gap-3 md:grid-cols-2">
                                        <div class="space-y-1">
                                            <Label class="panel-label-muted">{{ t('translations.field_name') }} · {{ sourceLocale.toUpperCase() }}</Label>
                                            <Input :model-value="section.name" disabled class="panel-input-readonly" />
                                        </div>
                                        <div class="space-y-1">
                                            <div class="flex items-center justify-between">
                                                <Label class="panel-label">{{ t('translations.field_name') }} · {{ activeLocale.toUpperCase() }}</Label>
                                                <button
                                                    type="button"
                                                    class="text-muted-foreground hover:text-primary"
                                                    :title="t('translations.copy_from_source')"
                                                    @click="copyFromSource('section', section.id, 'name')"
                                                >
                                                    <CopyIcon class="h-3 w-3" />
                                                </button>
                                            </div>
                                            <Input v-model="form[activeLocale].sections[section.id].name" class="panel-input" placeholder="—" />
                                        </div>
                                        <div class="space-y-1">
                                            <Label class="panel-label-muted">{{ t('translations.field_description') }} · {{ sourceLocale.toUpperCase() }}</Label>
                                            <Textarea :model-value="section.description ?? ''" disabled rows="2" class="panel-input-readonly resize-none" />
                                        </div>
                                        <div class="space-y-1">
                                            <div class="flex items-center justify-between">
                                                <Label class="panel-label">{{ t('translations.field_description') }} · {{ activeLocale.toUpperCase() }}</Label>
                                                <button
                                                    type="button"
                                                    class="text-muted-foreground hover:text-primary"
                                                    :title="t('translations.copy_from_source')"
                                                    @click="copyFromSource('section', section.id, 'description')"
                                                >
                                                    <CopyIcon class="h-3 w-3" />
                                                </button>
                                            </div>
                                            <Textarea v-model="form[activeLocale].sections[section.id].description" rows="2" class="panel-input resize-none" placeholder="—" />
                                        </div>
                                    </div>
                                </div>

                                <!-- Products -->
                                <div v-if="visibleProducts(section).length > 0" class="divide-y">
                                    <div
                                        v-for="product in visibleProducts(section)"
                                        :key="product.id"
                                        class="space-y-3 px-5 py-4"
                                    >
                                        <div class="flex items-center gap-2">
                                            <span class="rounded bg-foreground/10 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-foreground/80">
                                                {{ t('translations.product_label') }}
                                            </span>
                                            <p class="panel-label">{{ product.name }}</p>
                                        </div>
                                        <div class="grid grid-cols-1 gap-3 md:grid-cols-2">
                                            <div class="space-y-1">
                                                <Label class="panel-label-muted">{{ t('translations.field_name') }} · {{ sourceLocale.toUpperCase() }}</Label>
                                                <Input :model-value="product.name" disabled class="panel-input-readonly" />
                                            </div>
                                            <div class="space-y-1">
                                                <div class="flex items-center justify-between">
                                                    <Label class="panel-label">{{ t('translations.field_name') }} · {{ activeLocale.toUpperCase() }}</Label>
                                                    <button
                                                        type="button"
                                                        class="text-muted-foreground hover:text-primary"
                                                        :title="t('translations.copy_from_source')"
                                                        @click="copyFromSource('product', product.id, 'name')"
                                                    >
                                                        <CopyIcon class="h-3 w-3" />
                                                    </button>
                                                </div>
                                                <Input v-model="form[activeLocale].products[product.id].name" class="panel-input" placeholder="—" />
                                            </div>
                                            <div class="space-y-1">
                                                <Label class="panel-label-muted">{{ t('translations.field_description') }} · {{ sourceLocale.toUpperCase() }}</Label>
                                                <Textarea :model-value="product.description ?? ''" disabled rows="2" class="panel-input-readonly resize-none" />
                                            </div>
                                            <div class="space-y-1">
                                                <div class="flex items-center justify-between">
                                                    <Label class="panel-label">{{ t('translations.field_description') }} · {{ activeLocale.toUpperCase() }}</Label>
                                                    <button
                                                        type="button"
                                                        class="text-muted-foreground hover:text-primary"
                                                        :title="t('translations.copy_from_source')"
                                                        @click="copyFromSource('product', product.id, 'description')"
                                                    >
                                                        <CopyIcon class="h-3 w-3" />
                                                    </button>
                                                </div>
                                                <Textarea v-model="form[activeLocale].products[product.id].description" rows="2" class="panel-input resize-none" placeholder="—" />
                                            </div>
                                        </div>

                                        <!-- Ingredients sub-block -->
                                        <div v-if="product.ingredients && product.ingredients.length > 0" class="mt-3 rounded-lg border border-dashed bg-muted/10 p-3">
                                            <p class="mb-2 text-[11px] font-bold uppercase tracking-wider text-foreground/50">
                                                {{ t('translations.ingredients_label') }}
                                            </p>
                                            <div class="space-y-2">
                                                <div
                                                    v-for="ingredient in product.ingredients"
                                                    :key="ingredient.id"
                                                    class="grid grid-cols-1 gap-2 md:grid-cols-2"
                                                >
                                                    <div class="space-y-1">
                                                        <Label class="panel-label-muted text-[10px]">{{ t('translations.ingredient_name') }} · {{ sourceLocale.toUpperCase() }}</Label>
                                                        <Input :model-value="ingredient.name" disabled class="panel-input-readonly h-8 text-xs" />
                                                    </div>
                                                    <div class="space-y-1">
                                                        <div class="flex items-center justify-between">
                                                            <Label class="panel-label text-[10px]">{{ t('translations.ingredient_name') }} · {{ activeLocale.toUpperCase() }}</Label>
                                                            <button
                                                                type="button"
                                                                class="text-muted-foreground hover:text-primary"
                                                                :title="t('translations.copy_from_source')"
                                                                @click="copyFromSource('ingredient', ingredient.id, 'name')"
                                                            >
                                                                <CopyIcon class="h-3 w-3" />
                                                            </button>
                                                        </div>
                                                        <Input
                                                            v-model="form[activeLocale].ingredients[ingredient.id].name"
                                                            class="panel-input h-8 text-xs"
                                                            placeholder="—"
                                                        />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <p v-else class="px-5 py-6 text-center text-xs text-muted-foreground">
                                    {{ t('translations.no_matching_products') }}
                                </p>
                            </div>
                        </div>
                    </template>
                </template>

                <div
                    v-if="!menu.sections || menu.sections.length === 0"
                    class="flex flex-col items-center justify-center rounded-xl border-2 border-dashed py-16 text-center"
                >
                    <Sparkles class="mb-3 h-10 w-10 text-muted-foreground/30" />
                    <p class="text-sm text-muted-foreground">{{ t('translations.empty_menu') }}</p>
                </div>
            </template>
        </div>

        <!-- Sticky save bar -->
        <div
            v-if="hasMultilang && targetLocales.length > 0"
            class="pointer-events-none fixed inset-x-0 bottom-0 z-30 flex justify-center p-4"
        >
            <div
                class="pointer-events-auto flex items-center gap-3 rounded-full border bg-card/95 text-card-foreground px-4 py-2 shadow-lg backdrop-blur"
                :class="isDirty ? 'border-primary/40' : 'border-border'"
            >
                <span class="panel-label" :class="isDirty ? 'font-medium text-foreground' : 'text-muted-foreground'">
                    {{ isDirty ? t('translations.unsaved_changes') : t('translations.all_saved') }}
                </span>
                <Button size="sm" :disabled="!isDirty || saving" @click="save">
                    <Loader2 v-if="saving" class="mr-1.5 h-3.5 w-3.5 animate-spin" />
                    <Save v-else class="mr-1.5 h-3.5 w-3.5" />
                    {{ t('translations.save') }}
                </Button>
            </div>
        </div>
    </AppLayout>
</template>
