<?php

namespace App\Http\Controllers\Admin\Tenant;

use App\Actions\Menu\AutoGenerateMenuTranslations;
use App\Http\Controllers\Controller;
use App\Models\Ingredient;
use App\Models\Menu;
use App\Models\Plan;
use App\Models\Product;
use App\Models\Section;
use App\Models\Subscription;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Inertia\Response;

class TranslationController extends Controller
{
    public function show(Menu $menu, AutoGenerateMenuTranslations $autoGenerate): Response
    {
        $hasMultilang = $this->tenantHasMultilang();
        $sourceLocale = config('menulinker.source_locale', 'es');
        $supportedLocales = $this->buildSupportedLocales();

        $menu->load([
            'sections' => fn ($q) => $q->orderBy('id'),
            'sections.products' => fn ($q) => $q->orderBy('products.id'),
            'sections.products.ingredients',
        ]);

        // On first visit (no translations at all), auto-generate the first
        // target locale (EN) so the user has editable drafts.
        $autoGenerated = false;
        if ($hasMultilang && empty($menu->translations)) {
            $firstTarget = $this->firstTargetLocale($sourceLocale, $supportedLocales);
            if ($firstTarget) {
                $autoGenerated = $autoGenerate->execute($menu, targetLocale: $firstTarget, sourceLocale: $sourceLocale);
                if ($autoGenerated) {
                    $menu->load([
                        'sections' => fn ($q) => $q->orderBy('id'),
                        'sections.products' => fn ($q) => $q->orderBy('products.id'),
                        'sections.products.ingredients',
                    ]);
                }
            }
        }

        $enabledLocales = $this->enabledLocalesFor($menu, $sourceLocale);

        return Inertia::render('admin/tenant/menus/Translations', [
            'menu' => $menu,
            'hasMultilang' => $hasMultilang,
            'autoGenerated' => $autoGenerated,
            'sourceLocale' => $sourceLocale,
            'supportedLocales' => $supportedLocales,
            'enabledLocales' => $enabledLocales,
        ]);
    }

    public function update(Request $request, Menu $menu): RedirectResponse|JsonResponse
    {
        if (! $this->tenantHasMultilang()) {
            abort(403, 'Multi-language translations require a Business plan or higher.');
        }

        $validated = $request->validate([
            'menu' => ['sometimes', 'array'],
            'menu.translations' => ['sometimes', 'array'],
            'sections' => ['sometimes', 'array'],
            'sections.*.id' => ['required_with:sections', 'integer'],
            'sections.*.translations' => ['required_with:sections', 'array'],
            'products' => ['sometimes', 'array'],
            'products.*.id' => ['required_with:products', 'integer'],
            'products.*.translations' => ['required_with:products', 'array'],
            'ingredients' => ['sometimes', 'array'],
            'ingredients.*.id' => ['required_with:ingredients', 'integer'],
            'ingredients.*.translations' => ['required_with:ingredients', 'array'],
        ]);

        if (isset($validated['menu']['translations'])) {
            $menu->update(['translations' => $validated['menu']['translations']]);
        }

        if (! empty($validated['sections'])) {
            foreach ($validated['sections'] as $sectionData) {
                Section::where('id', $sectionData['id'])
                    ->where('tenant_id', tenant()->id)
                    ->update(['translations' => $sectionData['translations']]);
            }
        }

        if (! empty($validated['products'])) {
            foreach ($validated['products'] as $productData) {
                Product::where('id', $productData['id'])
                    ->where('tenant_id', tenant()->id)
                    ->update(['translations' => $productData['translations']]);
            }
        }

        if (! empty($validated['ingredients'])) {
            foreach ($validated['ingredients'] as $ingredientData) {
                Ingredient::where('id', $ingredientData['id'])
                    ->where('tenant_id', tenant()->id)
                    ->update(['translations' => $ingredientData['translations']]);
            }
        }

        return back()->with('success', 'Traducciones guardadas correctamente.');
    }

    /**
     * Add a new target locale to the menu and auto-generate its translations.
     */
    public function addLanguage(Request $request, Menu $menu, AutoGenerateMenuTranslations $autoGenerate): RedirectResponse
    {
        if (! $this->tenantHasMultilang()) {
            abort(403, 'Multi-language translations require a Business plan or higher.');
        }

        $sourceLocale = config('menulinker.source_locale', 'es');
        $supportedCodes = array_keys(config('menulinker.supported_locales', []));

        $validated = $request->validate([
            'locale' => ['required', 'string', Rule::in($supportedCodes), Rule::notIn([$sourceLocale])],
        ]);

        $autoGenerate->execute($menu, targetLocale: $validated['locale'], sourceLocale: $sourceLocale);

        return back()->with('success', 'Idioma añadido y traducciones generadas.');
    }

    /**
     * Remove a target locale entirely from menu, sections and products.
     */
    public function removeLanguage(Request $request, Menu $menu): RedirectResponse
    {
        if (! $this->tenantHasMultilang()) {
            abort(403, 'Multi-language translations require a Business plan or higher.');
        }

        $sourceLocale = config('menulinker.source_locale', 'es');

        $validated = $request->validate([
            'locale' => ['required', 'string', Rule::notIn([$sourceLocale])],
        ]);

        $locale = $validated['locale'];

        $strip = function (?array $translations) use ($locale): ?array {
            if (! is_array($translations)) {
                return $translations;
            }
            unset($translations[$locale]);

            return $translations;
        };

        $menu->load(['sections.products.ingredients']);

        $menu->update(['translations' => $strip($menu->translations)]);

        foreach ($menu->sections as $section) {
            $section->update(['translations' => $strip($section->translations)]);
            foreach ($section->products as $product) {
                $product->update(['translations' => $strip($product->translations)]);
                foreach ($product->ingredients as $ingredient) {
                    $ingredient->update(['translations' => $strip($ingredient->translations)]);
                }
            }
        }

        return back()->with('success', 'Idioma eliminado.');
    }

    /**
     * @return array<string, array{native: string, flag: string, code: string}>
     */
    private function buildSupportedLocales(): array
    {
        $raw = config('menulinker.supported_locales', []);
        $out = [];
        foreach ($raw as $code => $meta) {
            $out[$code] = [
                'code' => $code,
                'native' => $meta['native'] ?? strtoupper($code),
                'flag' => $meta['flag'] ?? '',
            ];
        }

        return $out;
    }

    /**
     * @param  array<string, array{code: string, native: string, flag: string}>  $supportedLocales
     * @return array<int, string>
     */
    private function enabledLocalesFor(Menu $menu, string $sourceLocale): array
    {
        $locales = [$sourceLocale];
        $inMenu = array_keys($menu->translations ?? []);
        foreach ($inMenu as $code) {
            if ($code !== $sourceLocale && ! in_array($code, $locales, true)) {
                $locales[] = $code;
            }
        }

        return $locales;
    }

    /**
     * @param  array<string, array{code: string, native: string, flag: string}>  $supportedLocales
     */
    private function firstTargetLocale(string $sourceLocale, array $supportedLocales): ?string
    {
        foreach (array_keys($supportedLocales) as $code) {
            if ($code !== $sourceLocale) {
                return $code;
            }
        }

        return null;
    }

    private function tenantHasMultilang(): bool
    {
        $tenantId = tenant()->id;

        $subscription = Subscription::where('tenant_id', $tenantId)
            ->latest()
            ->with('plan')
            ->first();

        $plan = $subscription?->plan ?? Plan::free();

        return (bool) ($plan?->has_multilang ?? false);
    }
}
